### ISSUE TITLE
Events have to be manually added

### ISSUE THREAD

**Issue by dhornbein** [dhornbein/denverfreelancing.com#4]
It would be better if events were added as data and automatically displayed on the site.

I know of two methods for achieving this.

1. Add events as data in `/data/events.yaml` - each event could be a data block something like this:

``` yaml
events:
- title: February Working Meetup
  date: 2019-02-26
  location: 1062 Delaware St. Denver CO 80204
  time: 
   start: 4pm
   end: 7pm
  desc: Come work on co-creating Better Together.
  links:
   facebook: url
   meetup: url
```
(there might be a better data structure, perhaps looking at the meetup API would or some data standard for events)

2. Add events as collections ([read jekyll docs on collections](https://jekyllrb.com/docs/collections/))

This is probably the better way to do this as it allows us to write a file for each event in a folder such as `_events/2019-02-26-work-jam.md` then data can be added using [front matter](https://jekyllrb.com/docs/front-matter/)

The event file would looks something like this:

``` markdown
---
title: February Working Meetup
date: 2019-02-26
location: 1062 Delaware St. Denver CO 80204
time: 
 start: 4pm
 end: 7pm
 facebook: url
 meetup: url
---

Come work on co-creating Better Together.

## more content here

It's written in Markdown
```

Jekyll's [post execpts](https://jekyllrb.com/docs/posts/#post-excerpts) might very well work for this too.

I suggest we go with the collection method!

Furthermore, the collection method would lend itself (probably) better for eventual event creation automation. An admin interface to create an event could very well make a meetup, facebook, and file on the website.
